### ISSUE TITLE
Request for hardware environment details

### ISSUE THREAD

**Issue by ZhouHao524** [cvlab-yonsei/One-Shot-TAS#2]
Hello,
Could you please share the hardware settings you used for this project? Specifically, I’d like to know details about your GPU, driver version, and CUDA version.
Thank you in advance!

**Comment by dlguswn3659** [comment]
Hello,

Here are the hardware settings I used for the project:

```
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
```

Let me know if you need any additional details!
