### ISSUE TITLE
Valid Version of supernet_train.py

### ISSUE THREAD

**Issue by wanjuun** [cvlab-yonsei/One-Shot-TAS#3]
Hi,
It seems there are multiple versions of **`supernet_train.py`** in the repository. Could you please clarify which one is the valid or main version to use?
Thank you for your help!

**Comment by dlguswn3659** [comment]
Hello,

Thank you for your inquiry. Currently, the codebase is under active development, so there are multiple versions of `supernet_train.py`.

For now, the main version to use is `supernet_train_sn2.py`. In the future, we plan to clean up the repository by keeping only the valid versions. Additionally, we will refactor the code to make hyperparameter tuning more convenient.

Let me know if you have any further questions!
