### ISSUE TITLE
Pillow Build Error

### ISSUE THREAD

**Issue by weiqiangli029** [cvlab-yonsei/One-Shot-TAS#5]
Hello,
Thank you for your amazing work on this project! I truly appreciate your efforts and contributions.
When using the project, I encountered the following error related to Pillow. Could you please advise how to resolve this issue?
```
Building wheels for collected packages: pillow
  Building wheel for pillow (setup.py) ... error
  ERROR: Command errored out with exit status 1:

.
.
.

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pillow
  Running setup.py clean for pillow
Failed to build pillow
```
Any guidance would be greatly appreciated. Thank you!

P.S. I created the issue using a different GitHub account (#1, #4), but they appear to be hidden. Do you know why that might be?

**Comment by dlguswn3659** [comment]
Hello,

To resolve the Pillow build error, please try running the following commands in your terminal:

```
sudo apt-get install python3-dev
pip install wheel
apt-get update
apt-get install build-essential
apt-get install libjpeg-dev
apt-get install libpng-dev libtiff-dev
pip install pillow==6.1.0
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html

```

After executing these commands, refer to the README file for additional setup instructions.

Let me know if you encounter any further issues!
